<template>
  <div>
    <Tree
      @on-select-change="treetabledata"
      :data="data5"
      :render="renderContent"
      class="demo-tree-render"
      select-node
    ></Tree>
    <Table stripe :columns="tablelist" :data="tabledata"></Table>
  </div>
</template>
<script>
export default {
  data() {
    return {
      data5: [
        {
          buildingNo: "1",
          buildingName: "1栋",
          label: "1栋",
          children: [
            {
              buildingNo: "1",
              buildingName: "1栋",
              floorNo: "1层",
              label: "1层",
              children: [
                {
                  buildingNo: "1",
                  buildingName: "1栋",
                  floorNo: "1层",
                  roomNo: "101",
                  label: "101",
                  children: [
                    {
                      buildingId: 28,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "1层",
                      floorSort: 1,
                      roomNo: "101",
                      roomSort: 1,
                      roomToward: "朝西",
                      bedId: 1,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      status: "预定",
                      oldId: 13,
                      groupId: 74,
                      wardId: 2,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "10101",
                      id: 13,
                      name: "钱佳份",
                      sex: "男",
                      birthday: "2005-01-13 09:09:00",
                    },
                    {
                      buildingId: 29,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "1层",
                      floorSort: 1,
                      roomNo: "101",
                      roomSort: 1,
                      roomToward: "朝西",
                      bedId: 2,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      status: "预定",
                      oldId: 14,
                      groupId: 74,
                      wardId: 2,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "10102",
                      id: 14,
                      name: "杨嘉语",
                      sex: "男",
                      birthday: "2005-01-13 09:09:00",
                    },
                    {
                      buildingId: 30,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "1层",
                      floorSort: 1,
                      roomNo: "101",
                      roomSort: 1,
                      roomToward: "朝西",
                      bedId: 3,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      status: "预定",
                      oldId: 15,
                      groupId: 74,
                      wardId: 2,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "10103",
                      id: 15,
                      name: "吴鸣豪",
                      sex: "男",
                      birthday: "2005-01-13 09:09:00",
                    },
                    {
                      buildingId: 31,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "1层",
                      floorSort: 1,
                      roomNo: "101",
                      roomSort: 1,
                      roomToward: "朝西",
                      bedId: 4,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      groupId: 74,
                      wardId: 2,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "10104",
                    },
                  ],
                },
                {
                  buildingNo: "1",
                  buildingName: "1栋",
                  floorNo: "1层",
                  roomNo: "102",
                  label: "102",
                  children: [
                    {
                      buildingId: 32,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "1层",
                      floorSort: 1,
                      roomNo: "102",
                      roomSort: 2,
                      roomToward: "朝西",
                      bedId: 1,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      groupId: 74,
                      wardId: 2,
                      areaId: 7,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "10201",
                    },
                    {
                      buildingId: 33,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "1层",
                      floorSort: 1,
                      roomNo: "102",
                      roomSort: 2,
                      roomToward: "朝西",
                      bedId: 2,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      groupId: 74,
                      wardId: 2,
                      areaId: 7,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "10202",
                    },
                    {
                      buildingId: 34,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "1层",
                      floorSort: 1,
                      roomNo: "102",
                      roomSort: 2,
                      roomToward: "朝西",
                      bedId: 3,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      groupId: 74,
                      wardId: 2,
                      areaId: 7,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "10203",
                    },
                    {
                      buildingId: 35,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "1层",
                      floorSort: 1,
                      roomNo: "102",
                      roomSort: 2,
                      roomToward: "朝西",
                      bedId: 4,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      groupId: 74,
                      wardId: 2,
                      areaId: 7,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "10204",
                    },
                  ],
                },
                {
                  buildingNo: "1",
                  buildingName: "1栋",
                  floorNo: "1层",
                  roomNo: "103",
                  label: "103",
                  children: [
                    {
                      buildingId: 36,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "1层",
                      floorSort: 1,
                      roomNo: "103",
                      roomSort: 3,
                      roomToward: "朝西",
                      bedId: 1,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      status: "入住",
                      oldId: 19,
                      groupId: 74,
                      wardId: 2,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "10301",
                      id: 19,
                      name: "金后丽",
                      sex: "男",
                      birthday: "2005-01-13 09:09:00",
                    },
                    {
                      buildingId: 37,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "1层",
                      floorSort: 1,
                      roomNo: "103",
                      roomSort: 3,
                      roomToward: "朝西",
                      bedId: 2,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      status: "入住",
                      oldId: 18,
                      groupId: 74,
                      wardId: 2,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "10302",
                      id: 18,
                      name: "陶昊龄",
                      sex: "男",
                      birthday: "2005-01-13 09:09:00",
                    },
                    {
                      buildingId: 38,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "1层",
                      floorSort: 1,
                      roomNo: "103",
                      roomSort: 3,
                      roomToward: "朝西",
                      bedId: 3,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      status: "入住",
                      oldId: 17,
                      groupId: 74,
                      wardId: 2,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "10303",
                      id: 17,
                      name: "吕虚身",
                      sex: "男",
                      birthday: "2005-01-13 09:09:00",
                    },
                    {
                      buildingId: 39,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "1层",
                      floorSort: 1,
                      roomNo: "103",
                      roomSort: 3,
                      roomToward: "朝西",
                      bedId: 4,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      status: "入住",
                      oldId: 16,
                      groupId: 74,
                      wardId: 2,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "10304",
                      id: 16,
                      name: "沈通在",
                      sex: "男",
                      birthday: "2005-01-13 09:09:00",
                    },
                  ],
                },
              ],
            },
            {
              buildingNo: "1",
              buildingName: "1栋",
              floorNo: "2层",
              label: "2层",
              children: [
                {
                  buildingNo: "1",
                  buildingName: "1栋",
                  floorNo: "2层",
                  roomNo: "201",
                  label: "201",
                  children: [
                    {
                      buildingId: 40,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "2层",
                      floorSort: 2,
                      roomNo: "201",
                      roomSort: 1,
                      roomToward: "朝西",
                      bedId: 1,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      status: "",
                      groupId: 74,
                      wardId: 2,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "20101",
                    },
                    {
                      buildingId: 41,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "2层",
                      floorSort: 2,
                      roomNo: "201",
                      roomSort: 1,
                      roomToward: "朝西",
                      bedId: 2,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      status: "入住",
                      oldId: 20,
                      groupId: 74,
                      wardId: 2,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "20102",
                      id: 20,
                      name: "吴成莹",
                      sex: "男",
                      birthday: "2005-01-13 09:09:00",
                    },
                    {
                      buildingId: 42,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "2层",
                      floorSort: 2,
                      roomNo: "201",
                      roomSort: 1,
                      roomToward: "朝西",
                      bedId: 3,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      groupId: 74,
                      wardId: 2,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "20103",
                    },
                    {
                      buildingId: 43,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "2层",
                      floorSort: 2,
                      roomNo: "201",
                      roomSort: 1,
                      roomToward: "朝西",
                      bedId: 4,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      groupId: 74,
                      wardId: 2,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "20104",
                    },
                  ],
                },
                {
                  buildingNo: "1",
                  buildingName: "1栋",
                  floorNo: "2层",
                  roomNo: "202",
                  label: "202",
                  children: [
                    {
                      buildingId: 44,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "2层",
                      floorSort: 2,
                      roomNo: "202",
                      roomSort: 2,
                      roomToward: "朝西",
                      bedId: 1,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      groupId: 74,
                      wardId: 2,
                      areaId: 7,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "20201",
                    },
                    {
                      buildingId: 45,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "2层",
                      floorSort: 2,
                      roomNo: "202",
                      roomSort: 2,
                      roomToward: "朝西",
                      bedId: 2,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      status: "入住",
                      oldId: 23,
                      groupId: 74,
                      wardId: 2,
                      areaId: 7,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "20202",
                      id: 23,
                      name: "马云1",
                      sex: "男",
                    },
                    {
                      buildingId: 46,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "2层",
                      floorSort: 2,
                      roomNo: "202",
                      roomSort: 2,
                      roomToward: "朝西",
                      bedId: 3,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      status: "入住",
                      oldId: 24,
                      groupId: 74,
                      wardId: 2,
                      areaId: 7,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "20203",
                    },
                    {
                      buildingId: 47,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "2层",
                      floorSort: 2,
                      roomNo: "202",
                      roomSort: 2,
                      roomToward: "朝西",
                      bedId: 4,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      groupId: 74,
                      wardId: 2,
                      areaId: 7,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "20204",
                    },
                  ],
                },
                {
                  buildingNo: "1",
                  buildingName: "1栋",
                  floorNo: "2层",
                  roomNo: "203",
                  label: "203",
                  children: [
                    {
                      buildingId: 48,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "2层",
                      floorSort: 2,
                      roomNo: "203",
                      roomSort: 3,
                      roomToward: "朝西",
                      bedId: 1,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      status: "入住",
                      oldId: 26,
                      groupId: 74,
                      wardId: 2,
                      areaId: 7,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "20301",
                    },
                    {
                      buildingId: 49,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "2层",
                      floorSort: 2,
                      roomNo: "203",
                      roomSort: 3,
                      roomToward: "朝西",
                      bedId: 2,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      status: "入住",
                      oldId: 27,
                      groupId: 74,
                      wardId: 2,
                      areaId: 7,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "20302",
                    },
                    {
                      buildingId: 50,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "2层",
                      floorSort: 2,
                      roomNo: "203",
                      roomSort: 3,
                      roomToward: "朝西",
                      bedId: 3,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      groupId: 74,
                      wardId: 2,
                      areaId: 7,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "20303",
                    },
                    {
                      buildingId: 51,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "2层",
                      floorSort: 2,
                      roomNo: "203",
                      roomSort: 3,
                      roomToward: "朝西",
                      bedId: 4,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      groupId: 74,
                      wardId: 2,
                      areaId: 7,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "20304",
                    },
                  ],
                },
              ],
            },
            {
              buildingNo: "1",
              buildingName: "1栋",
              floorNo: "3层",
              label: "3层",
              children: [
                {
                  buildingNo: "1",
                  buildingName: "1栋",
                  floorNo: "3层",
                  roomNo: "301",
                  label: "301",
                  children: [
                    {
                      buildingId: 52,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "3层",
                      floorSort: 3,
                      roomNo: "301",
                      roomSort: 1,
                      roomToward: "朝西",
                      bedId: 1,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      groupId: 74,
                      wardId: 2,
                      areaId: 7,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "30101",
                    },
                    {
                      buildingId: 53,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "3层",
                      floorSort: 3,
                      roomNo: "301",
                      roomSort: 1,
                      roomToward: "朝西",
                      bedId: 2,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      groupId: 74,
                      wardId: 2,
                      areaId: 7,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "30102",
                    },
                    {
                      buildingId: 54,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "3层",
                      floorSort: 3,
                      roomNo: "301",
                      roomSort: 1,
                      roomToward: "朝西",
                      bedId: 3,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      status: "入住",
                      oldId: 29,
                      groupId: 74,
                      wardId: 2,
                      areaId: 7,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "30103",
                    },
                    {
                      buildingId: 55,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "3层",
                      floorSort: 3,
                      roomNo: "301",
                      roomSort: 1,
                      roomToward: "朝西",
                      bedId: 4,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      groupId: 74,
                      wardId: 2,
                      areaId: 7,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "30104",
                    },
                  ],
                },
                {
                  buildingNo: "1",
                  buildingName: "1栋",
                  floorNo: "3层",
                  roomNo: "302",
                  label: "302",
                  children: [
                    {
                      buildingId: 56,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "3层",
                      floorSort: 3,
                      roomNo: "302",
                      roomSort: 2,
                      roomToward: "朝西",
                      bedId: 1,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      groupId: 74,
                      wardId: 2,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "30201",
                    },
                    {
                      buildingId: 57,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "3层",
                      floorSort: 3,
                      roomNo: "302",
                      roomSort: 2,
                      roomToward: "朝西",
                      bedId: 2,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      status: "入住",
                      oldId: 30,
                      groupId: 74,
                      wardId: 2,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "30202",
                    },
                    {
                      buildingId: 58,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "3层",
                      floorSort: 3,
                      roomNo: "302",
                      roomSort: 2,
                      roomToward: "朝西",
                      bedId: 3,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      status: "入住",
                      oldId: 31,
                      groupId: 74,
                      wardId: 2,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "30203",
                    },
                    {
                      buildingId: 59,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "3层",
                      floorSort: 3,
                      roomNo: "302",
                      roomSort: 2,
                      roomToward: "朝西",
                      bedId: 4,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      status: "入住",
                      oldId: 32,
                      groupId: 74,
                      wardId: 2,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "30204",
                    },
                  ],
                },
                {
                  buildingNo: "1",
                  buildingName: "1栋",
                  floorNo: "3层",
                  roomNo: "303",
                  label: "303",
                  children: [
                    {
                      buildingId: 60,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "3层",
                      floorSort: 3,
                      roomNo: "303",
                      roomSort: 3,
                      roomToward: "朝西",
                      bedId: 1,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      groupId: 74,
                      wardId: 2,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "30301",
                    },
                    {
                      buildingId: 61,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "3层",
                      floorSort: 3,
                      roomNo: "303",
                      roomSort: 3,
                      roomToward: "朝西",
                      bedId: 2,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      groupId: 74,
                      wardId: 2,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "30302",
                    },
                    {
                      buildingId: 62,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "3层",
                      floorSort: 3,
                      roomNo: "303",
                      roomSort: 3,
                      roomToward: "朝西",
                      bedId: 3,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      groupId: 74,
                      wardId: 2,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "30303",
                    },
                    {
                      buildingId: 63,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "3层",
                      floorSort: 3,
                      roomNo: "303",
                      roomSort: 3,
                      roomToward: "朝西",
                      bedId: 4,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      status: "预约",
                      groupId: 74,
                      wardId: 2,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "30304",
                    },
                  ],
                },
              ],
            },
            {
              buildingNo: "1",
              buildingName: "1栋",
              floorNo: "4层",
              label: "4层",
              children: [
                {
                  buildingNo: "1",
                  buildingName: "1栋",
                  floorNo: "4层",
                  roomNo: "401",
                  label: "401",
                  children: [
                    {
                      buildingId: 64,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "4层",
                      floorSort: 4,
                      roomNo: "401",
                      roomSort: 1,
                      roomToward: "朝西",
                      bedId: 1,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      status: "预约",
                      groupId: 74,
                      wardId: 2,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "40101",
                    },
                    {
                      buildingId: 65,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "4层",
                      floorSort: 4,
                      roomNo: "401",
                      roomSort: 1,
                      roomToward: "朝西",
                      bedId: 2,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      status: "预约",
                      groupId: 74,
                      wardId: 2,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "40102",
                    },
                    {
                      buildingId: 66,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "4层",
                      floorSort: 4,
                      roomNo: "401",
                      roomSort: 1,
                      roomToward: "朝西",
                      bedId: 3,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      status: "预约",
                      groupId: 74,
                      wardId: 2,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "40103",
                    },
                    {
                      buildingId: 67,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "4层",
                      floorSort: 4,
                      roomNo: "401",
                      roomSort: 1,
                      roomToward: "朝西",
                      bedId: 4,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      status: "预约",
                      groupId: 74,
                      wardId: 2,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "40104",
                    },
                  ],
                },
                {
                  buildingNo: "1",
                  buildingName: "1栋",
                  floorNo: "4层",
                  roomNo: "402",
                  label: "402",
                  children: [
                    {
                      buildingId: 68,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "4层",
                      floorSort: 4,
                      roomNo: "402",
                      roomSort: 2,
                      roomToward: "朝西",
                      bedId: 1,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      groupId: 74,
                      wardId: 2,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "40201",
                    },
                    {
                      buildingId: 69,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "4层",
                      floorSort: 4,
                      roomNo: "402",
                      roomSort: 2,
                      roomToward: "朝西",
                      bedId: 2,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      status: "预约",
                      groupId: 74,
                      wardId: 2,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "40202",
                    },
                    {
                      buildingId: 70,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "4层",
                      floorSort: 4,
                      roomNo: "402",
                      roomSort: 2,
                      roomToward: "朝西",
                      bedId: 3,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      groupId: 74,
                      wardId: 2,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "40203",
                    },
                    {
                      buildingId: 71,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "4层",
                      floorSort: 4,
                      roomNo: "402",
                      roomSort: 2,
                      roomToward: "朝西",
                      bedId: 4,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      groupId: 74,
                      wardId: 2,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "40204",
                    },
                  ],
                },
                {
                  buildingNo: "1",
                  buildingName: "1栋",
                  floorNo: "4层",
                  roomNo: "403",
                  label: "403",
                  children: [
                    {
                      buildingId: 72,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "4层",
                      floorSort: 4,
                      roomNo: "403",
                      roomSort: 3,
                      roomToward: "朝西",
                      bedId: 1,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      groupId: 74,
                      wardId: 2,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "40301",
                    },
                    {
                      buildingId: 73,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "4层",
                      floorSort: 4,
                      roomNo: "403",
                      roomSort: 3,
                      roomToward: "朝西",
                      bedId: 2,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      groupId: 74,
                      wardId: 2,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "40302",
                    },
                    {
                      buildingId: 74,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "4层",
                      floorSort: 4,
                      roomNo: "403",
                      roomSort: 3,
                      roomToward: "朝西",
                      bedId: 3,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      groupId: 74,
                      wardId: 2,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "40303",
                    },
                    {
                      buildingId: 75,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "4层",
                      floorSort: 4,
                      roomNo: "403",
                      roomSort: 3,
                      roomToward: "朝西",
                      bedId: 4,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      groupId: 74,
                      wardId: 2,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "40304",
                    },
                  ],
                },
              ],
            },
            {
              buildingNo: "1",
              buildingName: "1栋",
              floorNo: "5层",
              label: "5层",
              children: [
                {
                  buildingNo: "1",
                  buildingName: "1栋",
                  floorNo: "5层",
                  roomNo: "501",
                  label: "501",
                  children: [
                    {
                      buildingId: 76,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "5层",
                      floorSort: 5,
                      roomNo: "501",
                      roomSort: 1,
                      roomToward: "朝西",
                      bedId: 1,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      groupId: 74,
                      wardId: 2,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "50101",
                    },
                    {
                      buildingId: 77,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "5层",
                      floorSort: 5,
                      roomNo: "501",
                      roomSort: 1,
                      roomToward: "朝西",
                      bedId: 2,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      groupId: 74,
                      wardId: 2,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "50102",
                    },
                    {
                      buildingId: 78,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "5层",
                      floorSort: 5,
                      roomNo: "501",
                      roomSort: 1,
                      roomToward: "朝西",
                      bedId: 3,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      groupId: 74,
                      wardId: 2,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "50103",
                    },
                    {
                      buildingId: 79,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "5层",
                      floorSort: 5,
                      roomNo: "501",
                      roomSort: 1,
                      roomToward: "朝西",
                      bedId: 4,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      groupId: 74,
                      wardId: 2,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "50104",
                    },
                  ],
                },
                {
                  buildingNo: "1",
                  buildingName: "1栋",
                  floorNo: "5层",
                  roomNo: "502",
                  label: "502",
                  children: [
                    {
                      buildingId: 80,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "5层",
                      floorSort: 5,
                      roomNo: "502",
                      roomSort: 2,
                      roomToward: "朝西",
                      bedId: 1,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      groupId: 74,
                      wardId: 2,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "50201",
                    },
                    {
                      buildingId: 81,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "5层",
                      floorSort: 5,
                      roomNo: "502",
                      roomSort: 2,
                      roomToward: "朝西",
                      bedId: 2,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      groupId: 74,
                      wardId: 2,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "50202",
                    },
                    {
                      buildingId: 82,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "5层",
                      floorSort: 5,
                      roomNo: "502",
                      roomSort: 2,
                      roomToward: "朝西",
                      bedId: 3,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      groupId: 74,
                      wardId: 2,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "50203",
                    },
                    {
                      buildingId: 83,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "5层",
                      floorSort: 5,
                      roomNo: "502",
                      roomSort: 2,
                      roomToward: "朝西",
                      bedId: 4,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      groupId: 74,
                      wardId: 2,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "50204",
                    },
                  ],
                },
                {
                  buildingNo: "1",
                  buildingName: "1栋",
                  floorNo: "5层",
                  roomNo: "503",
                  label: "503",
                  children: [
                    {
                      buildingId: 84,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "5层",
                      floorSort: 5,
                      roomNo: "503",
                      roomSort: 3,
                      roomToward: "朝西",
                      bedId: 1,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      groupId: 74,
                      wardId: 2,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "50301",
                    },
                    {
                      buildingId: 85,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "5层",
                      floorSort: 5,
                      roomNo: "503",
                      roomSort: 3,
                      roomToward: "朝西",
                      bedId: 2,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      groupId: 74,
                      wardId: 2,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "50302",
                    },
                    {
                      buildingId: 86,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "5层",
                      floorSort: 5,
                      roomNo: "503",
                      roomSort: 3,
                      roomToward: "朝西",
                      bedId: 3,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      groupId: 74,
                      wardId: 2,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "50303",
                    },
                    {
                      buildingId: 87,
                      buildingNo: "1",
                      buildingName: "1栋",
                      floorNo: "5层",
                      floorSort: 5,
                      roomNo: "503",
                      roomSort: 3,
                      roomToward: "朝西",
                      bedId: 4,
                      bedType: 1,
                      bedToward: "朝南",
                      nursingType: "其他",
                      groupId: 74,
                      wardId: 2,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 0,
                      deptId: 1,
                      label: "50304",
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          buildingNo: "2",
          buildingName: "2栋",
          label: "2栋",
          children: [
            {
              buildingNo: "2",
              buildingName: "2栋",
              floorNo: "1层",
              label: "1层",
              children: [
                {
                  buildingNo: "2",
                  buildingName: "2栋",
                  floorNo: "1层",
                  roomNo: "101",
                  label: "101",
                  children: [
                    {
                      buildingId: 1,
                      buildingNo: "2",
                      buildingName: "2栋",
                      floorNo: "1层",
                      floorSort: 1,
                      roomNo: "101",
                      roomSort: 1,
                      roomToward: "朝北",
                      bedId: 1,
                      bedType: 1,
                      bedToward: "朝东",
                      nursingType: "自理",
                      status: "入住",
                      oldId: 1,
                      groupId: 74,
                      wardId: 1,
                      areaId: 1,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 1,
                      deptId: 2,
                      label: "10101",
                      id: 1,
                      name: "姜欣责",
                      sex: "男",
                      birthday: "1970-01-13 16:59:11",
                    },
                    {
                      buildingId: 2,
                      buildingNo: "2",
                      buildingName: "2栋",
                      floorNo: "1层",
                      floorSort: 1,
                      roomNo: "101",
                      roomSort: 1,
                      roomToward: "朝北",
                      bedId: 2,
                      bedType: 1,
                      bedToward: "朝东",
                      nursingType: "自理",
                      status: "入住",
                      oldId: 2,
                      groupId: 74,
                      wardId: 0,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 1,
                      deptId: 1,
                      label: "10102",
                      id: 2,
                      name: "金添林",
                      sex: "男",
                      birthday: "2022-02-10 00:00:00",
                    },
                    {
                      buildingId: 3,
                      buildingNo: "2",
                      buildingName: "2栋",
                      floorNo: "1层",
                      floorSort: 1,
                      roomNo: "101",
                      roomSort: 1,
                      roomToward: "朝北",
                      bedId: 3,
                      bedType: 1,
                      bedToward: "朝东",
                      nursingType: "自理",
                      status: "入住",
                      oldId: 3,
                      groupId: 74,
                      wardId: 1,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 1,
                      deptId: 2,
                      label: "10103",
                      id: 3,
                      name: "姜和真",
                      sex: "男",
                      birthday: "1989-06-18 09:47:11",
                    },
                  ],
                },
                {
                  buildingNo: "2",
                  buildingName: "2栋",
                  floorNo: "1层",
                  roomNo: "102",
                  label: "102",
                  children: [
                    {
                      buildingId: 4,
                      buildingNo: "2",
                      buildingName: "2栋",
                      floorNo: "1层",
                      floorSort: 1,
                      roomNo: "102",
                      roomSort: 2,
                      roomToward: "朝北",
                      bedId: 4,
                      bedType: 1,
                      bedToward: "朝东",
                      nursingType: "自理",
                      status: "预约",
                      oldId: 4,
                      groupId: 74,
                      wardId: 1,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 1,
                      deptId: 1,
                      label: "10204",
                      id: 4,
                      name: "赵份入",
                      sex: "男",
                      birthday: "1989-05-28 09:47:11",
                    },
                    {
                      buildingId: 5,
                      buildingNo: "2",
                      buildingName: "2栋",
                      floorNo: "1层",
                      floorSort: 1,
                      roomNo: "102",
                      roomSort: 2,
                      roomToward: "朝北",
                      bedId: 5,
                      bedType: 1,
                      bedToward: "朝东",
                      nursingType: "自理",
                      status: "入住",
                      oldId: 5,
                      groupId: 74,
                      wardId: 1,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 1,
                      deptId: 2,
                      label: "10205",
                      id: 5,
                      name: "杨栋活",
                      sex: "男",
                      birthday: "1986-07-08 09:47:11",
                    },
                    {
                      buildingId: 6,
                      buildingNo: "2",
                      buildingName: "2栋",
                      floorNo: "1层",
                      floorSort: 1,
                      roomNo: "102",
                      roomSort: 2,
                      roomToward: "朝北",
                      bedId: 6,
                      bedType: 1,
                      bedToward: "朝东",
                      nursingType: "自理",
                      status: "入住",
                      oldId: 6,
                      groupId: 74,
                      wardId: 1,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 1,
                      deptId: 2,
                      label: "10206",
                      id: 6,
                      name: "曹茜昕",
                      sex: "男",
                      birthday: "1992-09-23 09:47:11",
                    },
                  ],
                },
                {
                  buildingNo: "2",
                  buildingName: "2栋",
                  floorNo: "1层",
                  roomNo: "103",
                  label: "103",
                  children: [
                    {
                      buildingId: 7,
                      buildingNo: "2",
                      buildingName: "2栋",
                      floorNo: "1层",
                      floorSort: 1,
                      roomNo: "103",
                      roomSort: 3,
                      roomToward: "朝北",
                      bedId: 7,
                      bedType: 1,
                      bedToward: "朝东",
                      nursingType: "自理",
                      status: "入住",
                      oldId: 7,
                      groupId: 74,
                      wardId: 1,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 1,
                      deptId: 2,
                      label: "10307",
                      id: 7,
                      name: "华证轩",
                      sex: "男",
                      birthday: "1989-05-23 09:47:11",
                    },
                    {
                      buildingId: 8,
                      buildingNo: "2",
                      buildingName: "2栋",
                      floorNo: "1层",
                      floorSort: 1,
                      roomNo: "103",
                      roomSort: 3,
                      roomToward: "朝北",
                      bedId: 8,
                      bedType: 1,
                      bedToward: "朝东",
                      nursingType: "自理",
                      status: "入住",
                      oldId: 8,
                      groupId: 74,
                      wardId: 1,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 1,
                      deptId: 2,
                      label: "10308",
                      id: 8,
                      name: "蒋密添",
                      sex: "男",
                      birthday: "1991-09-13 00:00:00",
                    },
                    {
                      buildingId: 9,
                      buildingNo: "2",
                      buildingName: "2栋",
                      floorNo: "1层",
                      floorSort: 1,
                      roomNo: "103",
                      roomSort: 3,
                      roomToward: "朝北",
                      bedId: 9,
                      bedType: 1,
                      bedToward: "朝东",
                      nursingType: "自理",
                      status: "入住",
                      oldId: 9,
                      groupId: 74,
                      wardId: 1,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 1,
                      deptId: 2,
                      label: "10309",
                      id: 9,
                      name: "施宜冰",
                      sex: "女",
                      birthday: "1996-01-01 00:00:00",
                    },
                  ],
                },
              ],
            },
            {
              buildingNo: "2",
              buildingName: "2栋",
              floorNo: "2层",
              label: "2层",
              children: [
                {
                  buildingNo: "2",
                  buildingName: "2栋",
                  floorNo: "2层",
                  roomNo: "201",
                  label: "201",
                  children: [
                    {
                      buildingId: 10,
                      buildingNo: "2",
                      buildingName: "2栋",
                      floorNo: "2层",
                      floorSort: 2,
                      roomNo: "201",
                      roomSort: 1,
                      roomToward: "朝北",
                      bedId: 1,
                      bedType: 1,
                      bedToward: "朝东",
                      nursingType: "自理",
                      status: "入住",
                      oldId: 10,
                      groupId: 74,
                      wardId: 1,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 1,
                      deptId: 2,
                      label: "20101",
                      id: 10,
                      name: "孔和佳",
                      sex: "女",
                      birthday: "2003-03-13 09:09:00",
                    },
                    {
                      buildingId: 11,
                      buildingNo: "2",
                      buildingName: "2栋",
                      floorNo: "2层",
                      floorSort: 2,
                      roomNo: "201",
                      roomSort: 1,
                      roomToward: "朝北",
                      bedId: 2,
                      bedType: 1,
                      bedToward: "朝东",
                      nursingType: "自理",
                      status: "入住",
                      oldId: 11,
                      groupId: 74,
                      wardId: 1,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 1,
                      deptId: 2,
                      label: "20102",
                      id: 11,
                      name: "叶凡",
                      sex: "女",
                      birthday: "2005-04-13 09:09:00",
                    },
                    {
                      buildingId: 12,
                      buildingNo: "2",
                      buildingName: "2栋",
                      floorNo: "2层",
                      floorSort: 2,
                      roomNo: "201",
                      roomSort: 1,
                      roomToward: "朝北",
                      bedId: 3,
                      bedType: 1,
                      bedToward: "朝东",
                      nursingType: "自理",
                      status: "入住",
                      oldId: 12,
                      groupId: 74,
                      wardId: 1,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 1,
                      deptId: 2,
                      label: "20103",
                      id: 12,
                      name: "张玥用",
                      sex: "男",
                      birthday: "2005-01-13 09:09:00",
                    },
                  ],
                },
                {
                  buildingNo: "2",
                  buildingName: "2栋",
                  floorNo: "2层",
                  roomNo: "202",
                  label: "202",
                  children: [
                    {
                      buildingId: 13,
                      buildingNo: "2",
                      buildingName: "2栋",
                      floorNo: "2层",
                      floorSort: 2,
                      roomNo: "202",
                      roomSort: 2,
                      roomToward: "朝北",
                      bedId: 4,
                      bedType: 1,
                      bedToward: "朝东",
                      nursingType: "自理",
                      groupId: 74,
                      wardId: 1,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 1,
                      deptId: 2,
                      label: "20204",
                    },
                    {
                      buildingId: 14,
                      buildingNo: "2",
                      buildingName: "2栋",
                      floorNo: "2层",
                      floorSort: 2,
                      roomNo: "202",
                      roomSort: 2,
                      roomToward: "朝北",
                      bedId: 5,
                      bedType: 1,
                      bedToward: "朝东",
                      nursingType: "自理",
                      groupId: 74,
                      wardId: 1,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 1,
                      deptId: 2,
                      label: "20205",
                    },
                    {
                      buildingId: 15,
                      buildingNo: "2",
                      buildingName: "2栋",
                      floorNo: "2层",
                      floorSort: 2,
                      roomNo: "202",
                      roomSort: 2,
                      roomToward: "朝北",
                      bedId: 6,
                      bedType: 1,
                      bedToward: "朝东",
                      nursingType: "自理",
                      groupId: 74,
                      wardId: 1,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 1,
                      deptId: 2,
                      label: "20206",
                    },
                  ],
                },
                {
                  buildingNo: "2",
                  buildingName: "2栋",
                  floorNo: "2层",
                  roomNo: "203",
                  label: "203",
                  children: [
                    {
                      buildingId: 16,
                      buildingNo: "2",
                      buildingName: "2栋",
                      floorNo: "2层",
                      floorSort: 2,
                      roomNo: "203",
                      roomSort: 3,
                      roomToward: "朝北",
                      bedId: 7,
                      bedType: 1,
                      bedToward: "朝东",
                      nursingType: "自理",
                      groupId: 74,
                      wardId: 1,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 1,
                      deptId: 2,
                      label: "20307",
                    },
                    {
                      buildingId: 17,
                      buildingNo: "2",
                      buildingName: "2栋",
                      floorNo: "2层",
                      floorSort: 2,
                      roomNo: "203",
                      roomSort: 3,
                      roomToward: "朝北",
                      bedId: 8,
                      bedType: 1,
                      bedToward: "朝东",
                      nursingType: "自理",
                      groupId: 74,
                      wardId: 1,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 1,
                      deptId: 2,
                      label: "20308",
                    },
                    {
                      buildingId: 18,
                      buildingNo: "2",
                      buildingName: "2栋",
                      floorNo: "2层",
                      floorSort: 2,
                      roomNo: "203",
                      roomSort: 3,
                      roomToward: "朝北",
                      bedId: 9,
                      bedType: 1,
                      bedToward: "朝东",
                      nursingType: "自理",
                      groupId: 74,
                      wardId: 1,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 1,
                      deptId: 2,
                      label: "20309",
                    },
                  ],
                },
              ],
            },
            {
              buildingNo: "2",
              buildingName: "2栋",
              floorNo: "3层",
              label: "3层",
              children: [
                {
                  buildingNo: "2",
                  buildingName: "2栋",
                  floorNo: "3层",
                  roomNo: "301",
                  label: "301",
                  children: [
                    {
                      buildingId: 19,
                      buildingNo: "2",
                      buildingName: "2栋",
                      floorNo: "3层",
                      floorSort: 3,
                      roomNo: "301",
                      roomSort: 1,
                      roomToward: "朝北",
                      bedId: 1,
                      bedType: 1,
                      bedToward: "朝东",
                      nursingType: "自理",
                      groupId: 74,
                      wardId: 1,
                      areaId: 1,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 1,
                      deptId: 2,
                      label: "30101",
                    },
                    {
                      buildingId: 20,
                      buildingNo: "2",
                      buildingName: "2栋",
                      floorNo: "3层",
                      floorSort: 3,
                      roomNo: "301",
                      roomSort: 1,
                      roomToward: "朝北",
                      bedId: 2,
                      bedType: 1,
                      bedToward: "朝东",
                      nursingType: "自理",
                      groupId: 74,
                      wardId: 1,
                      areaId: 1,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 1,
                      deptId: 2,
                      label: "30102",
                    },
                    {
                      buildingId: 21,
                      buildingNo: "2",
                      buildingName: "2栋",
                      floorNo: "3层",
                      floorSort: 3,
                      roomNo: "301",
                      roomSort: 1,
                      roomToward: "朝北",
                      bedId: 3,
                      bedType: 1,
                      bedToward: "朝东",
                      nursingType: "自理",
                      groupId: 74,
                      wardId: 1,
                      areaId: 1,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 1,
                      deptId: 2,
                      label: "30103",
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          buildingNo: "3",
          buildingName: "3栋",
          label: "3栋",
          children: [
            {
              buildingNo: "3",
              buildingName: "3栋",
              floorNo: "3层",
              label: "3层",
              children: [
                {
                  buildingNo: "3",
                  buildingName: "3栋",
                  floorNo: "3层",
                  roomNo: "302",
                  label: "302",
                  children: [
                    {
                      buildingId: 22,
                      buildingNo: "3",
                      buildingName: "3栋",
                      floorNo: "3层",
                      floorSort: 3,
                      roomNo: "302",
                      roomSort: 2,
                      roomToward: "朝北",
                      bedId: 4,
                      bedType: 1,
                      bedToward: "朝东",
                      nursingType: "自理",
                      groupId: 74,
                      wardId: 1,
                      areaId: 1,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 1,
                      deptId: 2,
                      label: "30204",
                    },
                    {
                      buildingId: 23,
                      buildingNo: "3",
                      buildingName: "3栋",
                      floorNo: "3层",
                      floorSort: 3,
                      roomNo: "302",
                      roomSort: 2,
                      roomToward: "朝北",
                      bedId: 5,
                      bedType: 1,
                      bedToward: "朝东",
                      nursingType: "自理",
                      groupId: 74,
                      wardId: 1,
                      areaId: 1,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 1,
                      deptId: 2,
                      label: "30205",
                    },
                    {
                      buildingId: 24,
                      buildingNo: "3",
                      buildingName: "3栋",
                      floorNo: "3层",
                      floorSort: 3,
                      roomNo: "302",
                      roomSort: 2,
                      roomToward: "朝北",
                      bedId: 6,
                      bedType: 1,
                      bedToward: "朝东",
                      nursingType: "自理",
                      groupId: 74,
                      wardId: 1,
                      areaId: 1,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 1,
                      deptId: 1,
                      label: "30206",
                    },
                  ],
                },
                {
                  buildingNo: "3",
                  buildingName: "3栋",
                  floorNo: "3层",
                  roomNo: "303",
                  label: "303",
                  children: [
                    {
                      buildingId: 25,
                      buildingNo: "3",
                      buildingName: "3栋",
                      floorNo: "3层",
                      floorSort: 3,
                      roomNo: "303",
                      roomSort: 3,
                      roomToward: "朝北",
                      bedId: 7,
                      bedType: 1,
                      bedToward: "朝东",
                      nursingType: "自理",
                      groupId: 74,
                      wardId: 1,
                      areaId: 1,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 1,
                      deptId: 1,
                      label: "30307",
                    },
                    {
                      buildingId: 26,
                      buildingNo: "3",
                      buildingName: "3栋",
                      floorNo: "3层",
                      floorSort: 3,
                      roomNo: "303",
                      roomSort: 3,
                      roomToward: "朝北",
                      bedId: 8,
                      bedType: 1,
                      bedToward: "朝东",
                      nursingType: "自理",
                      groupId: 74,
                      wardId: 1,
                      areaId: 1,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 1,
                      deptId: 1,
                      label: "30308",
                    },
                    {
                      buildingId: 27,
                      buildingNo: "3",
                      buildingName: "3栋",
                      floorNo: "3层",
                      floorSort: 3,
                      roomNo: "303",
                      roomSort: 3,
                      roomToward: "朝北",
                      bedId: 9,
                      bedType: 1,
                      bedToward: "朝东",
                      nursingType: "自理",
                      groupId: 74,
                      wardId: 1,
                      areaId: 1,
                      bind: 1,
                      buildingJoinFloor: "",
                      floorJoinRoom: "",
                      roomJoinBed: "",
                      numbering: 1,
                      deptId: 1,
                      label: "30309",
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],

      tablelist: [],
      tabledata: [],
    };
  },
  methods: {
    renderContent(h, { root, node, data }) {
      return h(
        "span",
        {
          style: {
            display: "inline-block",
            width: "100%",
          },
          on: {
            click: () => {
              this.treetabledata(data);
            },
          },
        },
        [
          h("span", [h("span", data.label)]),
          h("span", {
            style: {
              display: "inline-block",
              float: "right",
              marginRight: "32px",
            },
          }),
        ]
      );
    },

    treetabledata(data) {
      console.log(data);
      this.tablelist = [];
      this.tabledata = [];
      console.log(data.children);
      if (data.children !== undefined) {
        for (let key in data.children[0]) {
          if (key !== "children") {
            let obj = { title: "", key: key };
            this.tablelist.push(obj);
          }
        }
        this.tabledata = data.children;
        console.log(this.tablelist);
        console.log(this.tabledata);
      } else if (data.children == undefined) {
        for (let key in data) {
          let obj = { title: "", key: key };
          this.tablelist.push(obj);
        }
        this.tabledata.push(data) ;
        console.log(this.tablelist);
        console.log(this.tabledata);
      }
    },
  },
};
</script>
<style>
.demo-tree-render .ivu-tree-title {
  width: 100%;
}
</style>
